### ISSUE TITLE
Please allow generating code into a stream

### ISSUE THREAD

**Issue by MatejQ** [exostasis/Exostasis.QR#1]
Current version only allows to generate code into a file. We need to generate it into a stream so that it can be output as ActionResult of an ASP.NET MVC controller.

**Comment by exostasis** [comment]
Sure honestly that is a way better implementation too because then my library would just return a stream and you would handle as need be.

**Comment by exostasis** [comment]
I have released 1.0.1 with support for writing to streams. I will now close this
